# Generated by Django 2.2.28 on 2022-06-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stupwd',
            fields=[
                ('id', models.CharField(blank=True, max_length=12, primary_key=True, serialize=False)),
                ('pwd', models.CharField(blank=True, max_length=12, null=True)),
                ('name', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'stupwd',
                'managed': False,
            },
        ),
    ]
