# Generated by Django 2.2.28 on 2022-06-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_detail', '0002_stupwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pwd', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
    ]
